### ISSUE TITLE
Images not loading in the website

### ISSUE THREAD

**Issue by lucasleon2107** [openrndr/openrndr.org#42] opened 2023-02-24 19:20 UTC
<img width="2232" alt="image" src="https://user-images.githubusercontent.com/4566949/221271844-39fb6267-b779-4699-82fe-042c5e5e6955.png">

**Comment by edwinRNDR** [comment] 2023-03-06 09:46
It seems to have been resolved without any our efforts. @BoydRotgans can you look into what went wrong in the first place and update this issue.

**Comment by BoydRotgans** [comment] 2023-03-07 17:03
@lucasleon2107 Thank you very much for addressing this problem! I've looked into this today and the cause can be simply explained by unusual high amount of visitors because of a [live stream](https://www.youtube.com/watch?v=GevzngfRnGw). Our hosting tire was not prepared for that. 

Currently the activity is back to normal so the images will be fine again. It's a good lessen learned.

**Closed by BoydRotgans** 2023-03-07 17:03 UTC
